# Generated by Django 3.1.3 on 2020-11-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='User',
            new_name='user',
        ),
    ]
